### ISSUE TITLE
can not find RANSAC.h and gnuplot.h

### ISSUE THREAD

**Issue by dywuha** [itsuhane/AdevAnalysis#1]
Hi,
  I have cloned your code and going to estimate the noise density of my imu. However, I can't find the gnuplot.h even though I have installed the gnuplot.
  Can you offer these files?
  And sorry for my poor English, I can't type Chinese on this computer

**Comment by itsuhane** [comment]
You can find this file in my other repo.
https://github.com/itsuhane/propitious-octo-adventure/blob/master/gnuplot.h
Sorry that I forgot to include this file.

**Comment by itsuhane** [comment]
The file is added, hope it solves your problem.

**Comment by dywuha** [comment]
Thank you!!!
